export const data = [
  {
    course: 'Introduction to Computer Science',
    professor: 'Dr. Smith',
    howInterestingRating: 85,
    howEasyRating: 65,
  },
  {
    course: 'Advanced Physics',
    professor: 'Prof. Johnson',
    howInterestingRating: 90,
    howEasyRating: 50,
  },
  {
    course: 'History of Art',
    professor: 'Dr. Anderson',
    howInterestingRating: 75,
    howEasyRating: 80,
  },
  {
    course: 'Mathematics Fundamentals',
    professor: 'Prof. Brown',
    howInterestingRating: 60,
    howEasyRating: 75,
  },
  {
    course: 'Literature and Society',
    professor: 'Dr. Williams',
    howInterestingRating: 92,
    howEasyRating: 70,
  },
  {
    course: 'Chemistry Basics',
    professor: 'Prof. Davis',
    howInterestingRating: 70,
    howEasyRating: 60,
  },
  {
    course: 'Psychology 101',
    professor: 'Dr. Martinez',
    howInterestingRating: 80,
    howEasyRating: 85,
  },
  {
    course: 'Economics Principles',
    professor: 'Prof. Taylor',
    howInterestingRating: 75,
    howEasyRating: 70,
  },
  {
    course: 'Environmental Science',
    professor: 'Dr. Adams',
    howInterestingRating: 85,
    howEasyRating: 55,
  },
  {
    course: 'Sociology of Culture',
    professor: 'Dr. White',
    howInterestingRating: 88,
    howEasyRating: 68,
  },
  {
    course: 'Political Science',
    professor: 'Prof. Walker',
    howInterestingRating: 70,
    howEasyRating: 75,
  },
  {
    course: 'Spanish Language',
    professor: 'Prof. Garcia',
    howInterestingRating: 92,
    howEasyRating: 82,
  },
  {
    course: 'Engineering Ethics',
    professor: 'Dr. Lee',
    howInterestingRating: 80,
    howEasyRating: 70,
  },
  {
    course: 'Health and Wellness',
    professor: 'Dr. Moore',
    howInterestingRating: 65,
    howEasyRating: 90,
  },
  {
    course: 'Literary Analysis',
    professor: 'Prof. Clark',
    howInterestingRating: 78,
    howEasyRating: 75,
  },
  {
    course: 'World History',
    professor: 'Dr. Robinson',
    howInterestingRating: 85,
    howEasyRating: 78,
  },
  {
    course: 'Introduction to Philosophy',
    professor: 'Dr. Baker',
    howInterestingRating: 90,
    howEasyRating: 65,
  },
  {
    course: 'Music Appreciation',
    professor: 'Prof. Adams',
    howInterestingRating: 72,
    howEasyRating: 80,
  },
  {
    course: 'Business Management',
    professor: 'Prof. Turner',
    howInterestingRating: 75,
    howEasyRating: 72,
  },
  {
    course: 'Physical Education',
    professor: 'Dr. Johnson',
    howInterestingRating: 60,
    howEasyRating: 95,
  },
];
