const DRAWER_WIDTH = 375;
// const DRAWER_LEFT_OVERFLOW_WIDTH = 90;
// const DRAWER_CONTENT_WIDTH = DRAWER_WIDTH * 0.67;
// const CLOSED_DRAWER_DRAGGABLE_SPACE = 0;
//
// const CLOSED_DRAWER_X = -DRAWER_WIDTH;
// const OPENED_DRAWER_X = 0;
//
// const START_SPACE = 25;
//
// const MINIMAL_SWIPE_DISTANCE = 50;
// const MINIMAL_SWIPE_TIME = 100;
//
//
// const OPENED_DRAWER_ANIMATION_NAME = 'opened-drawer';
// const CLOSED_DRAWER_ANIMATION_NAME = 'closed-drawer';
//


const DRAG_THRESHOLD = 10;
const SWIPEABLE_AREA = 1000;

export {
    DRAG_THRESHOLD,
    SWIPEABLE_AREA,
    DRAWER_WIDTH
}