const DRAWER_WIDTH = 320;
const DRAWER_CONTENT_WIDTH = DRAWER_WIDTH * 0.67;
const CLOSED_DRAWER_DRAGGABLE_SPACE = 0;

const DRAWER_LEFT_OVERFLOW_WIDTH = DRAWER_WIDTH - DRAWER_CONTENT_WIDTH;
const CLOSED_DRAWER_X = -DRAWER_WIDTH + CLOSED_DRAWER_DRAGGABLE_SPACE;
const OPENED_DRAWER_X = DRAWER_CONTENT_WIDTH - DRAWER_WIDTH;

const OPENED_DRAWER_ANIMATION_NAME = 'opened-drawer';
const CLOSED_DRAWER_ANIMATION_NAME = 'closed-drawer';

export {
    DRAWER_WIDTH,
    DRAWER_CONTENT_WIDTH,
    CLOSED_DRAWER_DRAGGABLE_SPACE,
    DRAWER_LEFT_OVERFLOW_WIDTH,
    CLOSED_DRAWER_X,
    OPENED_DRAWER_X,
    OPENED_DRAWER_ANIMATION_NAME,
    CLOSED_DRAWER_ANIMATION_NAME
}