name: CI

on:
  pull_request:
    branches:
      - develop

jobs:  
  build-pr-develop-and-run-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker versions
        run: |
          echo ---Docker version---
          docker --version
          echo ---Docker compose version---
          docker-compose --version

      - name: Docker compose
        id: docker-compose
        run: |
          echo ---Starting docker compose---
          docker-compose -f docker-compose-ci.yaml up --build -d
          echo ---Containers up---

      - uses: actions/setup-node@v4
        with:
          node-version: 18.18
      - run: npm install
      - run: npm -w backend run test:e2e
