name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build-pr-develop-and-run-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18.18
      - run: yarn install

      - name: Run frontend unit tests
        run: yarn workspace frontend test:unit

      - name: Upgrade docker compose
        run: |
          echo ---Upgrading docker compose---
          sudo rm -rf docker-compose
          sudo rm -rf /usr/bin/docker-compose
          sudo rm -rf /usr/local/bin/docker-compose
          sudo apt-get remove docker-compose-plugin
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-linux-x86_64" -o /usr/bin/docker-compose
          sudo chmod +x /usr/bin/docker-compose
          echo ---Docker version---
          docker --version
          echo ---Docker compose version---
          docker-compose --version

      - name: Docker compose
        id: docker-compose
        run: |
          echo ---Starting docker compose---
          docker-compose -f docker-compose-ci.yaml up --build -d
          echo ---Containers up---

      - name: Run backend e2e tests
        run: yarn workspace backend test:e2e

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Prepare frontend e2e tests
        run: yarn workspace backend bootstrap:frontendE2E

      - name: Run frontend e2e tests
        run: yarn workspace frontend test:e2e:ci