name: Deploy to DigitalOcean

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Version tag
        id: github-tag
        run: |
          echo "Reading package.json from ./package.json"
          PACKAGE_VERSION=$(cat ./package.json | jq '.version' | tr -d '"')
          echo "current-version=${PACKAGE_VERSION}" >> $GITHUB_OUTPUT
          exit 1
      - name: Docker login, build, tag, and push image to DigitalOcean
        id: build-image
        env:
            DO_REPOSITORY: ${{ vars.DO_REPOSITORY }} 
            DO_IMAGE_NAME: ${{ vars.DO_IMAGE_NAME }} 
            IMAGE_TAG: ${{ github.ref_name }}
        run: |
          # Login
          docker login $DO_REPOSITORY --username ${{ secrets.DIGITAL_OCEAN_TOKEN }} --password ${{ secrets.DIGITAL_OCEAN_TOKEN }}
          # Build a docker container and
          docker build -f ./backend/Dockerfile -t $DO_REPOSITORY/$DO_IMAGE_NAME:$IMAGE_TAG .
          docker push $DO_REPOSITORY/$DO_IMAGE_NAME:$IMAGE_TAG
          echo "image=$DO_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.6 # replace this with current version from https://github.com/digitalocean/app_action/releases
        with:
          app_name: my_DO_app
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: '[
                    {
                      "name": "sample-golang",
                      "image":{
                        "registry_type": "DOCR",
                        "repository": "add_sample",
                        "tag": "a5cae3e"
                      },
                    },
                    {
                      "name": "sample-add",
                      "image":{
                        "registry_type": "DOCKER_HUB",
                        "registry": "nginxdemos",
                        "repository": "hello",
                        "tag": "0.2"
                      },
                  ]'
