name: Staging Open PR from Develop
permissions:
  contents: write
  pull-requests: write
on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: "Version bump (major minor patch)"
        type: choice
        options:
          - "major"
          - "minor"
          - "patch"
        default: "patch"
jobs:
  staging-open-pr-from-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify if run from develop
        run: |
          if [ "${{ github.ref }}" != "refs/heads/develop" ]; then
            echo "Workflow is NOT triggered from develop"
            exit 1
          fi
          echo "Workflow is triggered from develop"

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.18

      - name: Bump version
        id: version-bump
        run: |
          echo "Bumping version type ${{ github.event.inputs.version_bump }}"
          npm --no-commit-hooks --no-git-tag-version version ${{ github.event.inputs.version_bump }}
          PACKAGE_VERSION=$(cat ./package.json | jq '.version' | tr -d '"')
          echo "Package version after bump: ${PACKAGE_VERSION}"
          echo "current-version=${PACKAGE_VERSION}" >> $GITHUB_OUTPUT

      - name: Commit new version
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Bump version ${{ steps.version-bump.outputs.current-version }}"
          git push origin develop

      - name: Create branch from develop
        run: |
          git checkout -b release/staging/v${{ steps.version-bump.outputs.current-version }} develop
          git push --set-upstream origin release/staging/v${{ steps.version-bump.outputs.current-version }} 

      - name: Create pull request
        run: gh pr create -B staging -H release/staging/v${{ steps.version-bump.outputs.current-version }} --title 'Release staging v${{ steps.version-bump.outputs.current-version }}' --body 'Staging release'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN_FOR_WORKFLOW_TRIGGER }}
